### ISSUE TITLE
OVH

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1037]
This card is about having a documented way to deploy on OVH

**Additional context**
Part of #208 

## Requirements
 - [ ] Check if it's possible to create a packer template that leverages https://github.com/rancher-sandbox/cos-toolkit-docs/pull/59 for installation, before attempting to create specific images
 - [ ] packer templates for Proxmox
 - [ ] docs explaining how to deploy on OVH

**Comment by mudler** [comment]
I've tried to deploy on OVH manually following https://rancher-sandbox.github.io/cos-toolkit-docs/docs/getting-started/install/#installation-from-3rd-party-livecd-or-rescue-mediums and I was able to deploy a cOS derivative, here are the summarized steps:

- From the Dedicated control panel, Enable rescue boot with Netboot->Rescue
- Boot over ssh, [install docker](https://docs.docker.com/engine/install/debian/) and run:
```
root@rescue:~# export DEVICE=/dev/sda
root@rescue:~# export IMAGE=<your IMAGE reference>
root@rescue:~# docker run --privileged -v $DEVICE:$DEVICE -ti quay.io/costoolkit/releases-green:cos-system-0.7.11-5 cos-installer --no-cosign --no-verify --docker-image $IMAGE $DEVICE
```

I've tested this with `IMAGE` `quay.io/mudler/c3os:v1.21.4-19`

**Comment by pgonin** [comment]
You could also directly used qcow2 and cloud-init on OVH bare metal
https://blog.ovhcloud.com/how-do-we-deploy-cloud-ready-images-on-bare-metal-servers/

**Comment by mudler** [comment]
> You could also directly used qcow2 and cloud-init on OVH bare metal https://blog.ovhcloud.com/how-do-we-deploy-cloud-ready-images-on-bare-metal-servers/

Seems not there yet for baremetals? 

> And if you’re up to the challenge, maybe make your own image to install it on your fresh servers with the soon-to-come Bring Your Own Image feature that is in development right now!
