### ISSUE TITLE
[blue] Boot stuck on aarch64 platform 

### ISSUE THREAD

**Issue by Ludea** [rancher/elemental-toolkit#1101]
**cos-toolkit version:**

Latest
**CPU architecture, OS, and Version:**

Aarch64 (Rpi3) 

**Describe the bug**

I created a derivative (fedora flavor) for both x64 and Rpi64 platform. 
When booting on Rpi3, I can see grub list, but when kernel boot, I get 
```
EFI STUB booting Linux Kernel... 
EFI_RNG_PROTOCOL unavailable 
ERROR : FIRMWARE BUG kernel image not aligned on 64k boundary 
ERROR : FIRMWARE BUG : Image BSS overlaps adjacent EFI memory region 
Using DTB from configuration file 
Exiting boot service 
```
**To Reproduce**

Create a derivative, based on Fedora, use arm-builder.sh to create Iso and burn it with Rpi imager
**Expected behavior**

Boot on my derivative flavor
**Logs**

**Additional context**

https://github.com/Ludea/sgnOS

**Comment by kkaempf** [comment]
does this still happen ?

**Comment by Ludea** [comment]
I switch to c3os.
So I don't know if there is a bug

**Comment by Ludea** [comment]
Closing this.
I will reopen if I decide to use fedora derivative and hit this issue
