### ISSUE TITLE
cloud-init: Encoding standard-cloud init into stages

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1124]
`yip` at the moment is inconsistent and encodes standard-cloud init syntax (NOT our extended syntax) into `boot` and `initramfs` stage: https://github.com/mudler/yip/blob/master/pkg/schema/loader_cloudinit.go#L111

This forces to do workarounds like https://github.com/rancher-sandbox/os2/pull/14#discussion_r804525767 while loading from datasources, but on the other hand we don't have any other cleaner mechanism to do so.

We don't directly encode them into `network`, because that would leave users configuring networking settings in the cold.

_Originally posted by @mudler in https://github.com/rancher-sandbox/os2/pull/14#discussion_r804525767_

**Comment by frelon** [comment]
Not sure this is needed anymore, closing
