### ISSUE TITLE
ARM support for Elemental

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1138]
Currently Elemental support for arm64 is just experimental and not tested, probably not functional at all. cOS is supporting arm64, and indeed being used by other derivatives too (e.g. [c3os](https://github.com/c3os-io/c3os)).

This card is a spike to figure out all the needed steps in order to support arm64 in Elemental(and derivatives), cOS changes included.

To keep in mind that rpi4 doesn't have TPM, that might be tricky in regards to Elemental

ping @kkaempf for any changes that might impact OBS

**Comment by mudler** [comment]
https://github.com/rancher/os2/issues/16 is a dup of this one

**Comment by mazzy89** [comment]
I gave a quick look to start the work for the arm64 building. At the moment being dapper not availlable for Apple M1, I do not have any Linux arm64 available instance where to run the build steps. The availability of RPIs do not help at all. I’m going to have an RPI in my hands in almost 10 days. Naturally I would like to avoid to do a cross-compile work at the moment.

**Comment by kkaempf** [comment]
We believe that everything is done on the Elemental side to support arm64. However, cluster deployment by Rancher on arm64 is not supported yet.
Closing.
