### ISSUE TITLE
Documentation: minimal required disk space

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-toolkit#115]
#### Environment

- openSUSE Tumbleweed
- git checkout of cOS-Toolkit
- docker 20.10.6

#### Steps to reproduce

- freshly installed docker
- about 16GB free on `/`
- empty `/var/lib/docker`
- `. .envrc`
- `cos-build`

#### Expected behavior

Successful build of a sample (minimal?) cOS

#### Actual behavior

After some minutes, the disk is full and I see

```
> df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p4   50G   38G     0 100% /

> sudo du -sh /var/lib/docker/
100G	/var/lib/docker/
```

#### Open questions

- do we know how disk space is used ?
- can we generate a smaller image ?

**Comment by mudler** [comment]
There is little we can do. During build multiple images are created - the only action Item I see here is documenting the required space for building the cos-toolkit repository and ways to cleanup afterwards.

Locally to cleanup the cache I do something among the lines of:

```bash
$ docker images --filter='reference=quay.io/xx/xx' --format='{{.Repository}}:{{.Tag}}' | xargs -r docker rmi
$ docker image prune
```

or to cleanup all: ` docker system prune --force --volumes --all`

**Comment by Itxaka** [comment]
Is this valid anymore @kkaempf ?
