### ISSUE TITLE
Need meta/cos-minimal variant for openSUSE/SLE builds

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-toolkit#1151]
**Is your feature request related to a problem? Please describe.**

As we're trying to build most parts [in the build service](https://build.opensuse.org/project/show/home:kwk:elemental), the current `meta/cos-minimal` conflicts with this as it overwrites e.g. `/usr/bin/elemental`

**Describe the solution you'd like**

A `meta/cos-minimal` variant which does NOT install (resp. overwrites) the OBS-built packages
* elemental
* os2 (ros-installer, ros-updater, ...(
* luet
* luet-makeiso

**Describe alternatives you've considered**

Build everything in Github

**Additional context**

**Comment by mudler** [comment]
I think what you need here is : meta/cos-modules. That should pull on everything else than binaries

**Comment by mudler** [comment]
FYI, docs: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/packages/meta-packages/meta-cos-modules/
