### ISSUE TITLE
Switch os2 to use NetworkManager

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1255]
After https://github.com/rancher-sandbox/cOS-toolkit/issues/1228 is completed we know all the required bits to move `os2` from wicked to `NetworkManager`, this card is about switching from `wicked` to `NetworkManager` in `os2`

## Action items
- [ ] Move the `os2` networking configs over `NetworkManager`
- [ ] Adapt documentation if needed
- [ ] QA, sanity check

**Comment by kkaempf** [comment]
Do we have a final decision on this topic from SLE Micro ?

**Comment by kkaempf** [comment]
Done with Elemental Teal 5.3
