### ISSUE TITLE
`elemental` cli to embed statically snapshots of the framework in releases

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1305]
This card is about having an "extended" version of the compiled elemental-cli binary with profile bundles that can be installed.

In this way, we can release elemental-cli binary which includes a set of profiles that can be installed while building a derivative for example with (`airgap-install` here is completely made up, looking for improvement) `elemental airgap-install <profile>` .

While building the "extended" elemental-cli, we create the profiles with the not-extended-`elemental` cli, which then are embedded into the extended version with the golang `embed` native feature. e.g. We could just use go generate tags for this.

This allows then whoever is building a derivative to do something like the following in the Dockerfiles (applies to sandboxed builds as well):

```Dockerfile
FROM <base image>
FROM <elemental_extended_image_cosigned> as tool

...

RUN elemental airgap-install <profile>

...
RUN mkinitrd 

```

See also https://github.com/rancher-sandbox/elemental/commit/048ab0b39b1713f350930ce159852b52948a0dbc for a quick sketch up of the above (missing CLI hooks, that's just a basic skeleton/draft).

This mechanism ideally would replace static framework assets included in the Dockerfile currently used for sandboxed builds. For example, in [os2](https://github.com/rancher-sandbox/os2/tree/master/framework/cos) since we switched to [teal](https://github.com/rancher-sandbox/os2/pull/119) we bundle the framework statically in the source to help on sandboxed builds (OBS). But this approach is rather difficult to sustain.

**Comment by Itxaka** [comment]
hey this sounds cool, let me read more abo

> We could just use go generate tags for this.

:runner: :dagger: :skull: :dagger: :skull: :dagger: :skull:

**Comment by mudler** [comment]
> hey this sounds cool, let me read more abo
> 
> > We could just use go generate tags for this.
> 
> runner dagger skull dagger skull dagger skull

:rofl: no need to use go generate, everything else to prepare the assets would work as well. go generate just make it tight to the code so what it does is more obvious in the code context, but that's just one way of doing this

**Comment by mudler** [comment]
Closing. While this is not needed, it is a tempting idea for other aspects. Although there is no specific interest in this feature
