### ISSUE TITLE
Elemental SELinux support

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1326]
As part of https://github.com/rancher-sandbox/os2/pull/119 SELinux was disabled from cmdline options.

Previous versions of os2 (not based on SLE Micro for Rancher) enabled selinux, but as the base image (openSUSE) didn't had support for it, it was silently ignored.

With SLE Micro for Rancher that has full SELinux support, os2 was not capable of booting anymore, as we don't have SELinux profiles.

This card is about having basic SELinux profile which would allow cOS to be functional under SELinux environments.

Currently, from my tests, even booting is prevented, as access to `/usr/local` is denied for several components. To replicate, is enough booting os2 with the `security=selinux selinux=1` boot commands.

See also: https://rancher-sandbox.github.io/cOS-toolkit/docs/reference/selinux/ and check if the elemental-cli  can re-apply the SELinux labels after install/upgrade/reset.

## Action items
- Check if the elemental-cli SELinux relabel section is working correctly
- Create a basic SELinux profile for cOS

**Comment by Itxaka** [comment]
weird because cos boots with teal and selinux enabled. it spits a lots of access denied, but it still boots no problems :o

**Comment by kkaempf** [comment]
Are the cloud-config settings applied ? Can you log in as root ?
We hud troubles here until selinux got disabled.

**Comment by Itxaka** [comment]
yep, I also was surprised. This is using the vagrant box generated by https://github.com/rancher-sandbox/cOS-toolkit/pull/1321

**Comment by mudler** [comment]
> weird because cos boots with teal and selinux enabled. it spits a lots of access denied, but it still boots no problems :o

mmm can you check if in the cmdline if selinux is set to permissive?

**Comment by Itxaka** [comment]
It has to be, otherwise it would fail, but If im reading it correctly that its set on the grub line `selinux=1`, doesnt os2 sets the same?

**Comment by Itxaka** [comment]
We should probably export that somehow so it can be set from env or or something while building instead of it being hardcoded

**Comment by mudler** [comment]
mmm by looking at https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/grub2/config/bootargs.cfg.tmpl#L5 doesn't look like we are booting in permissive mode on cOS?

**Comment by mudler** [comment]
Maybe just a different `/etc/selinux/config` configuration file?

**Comment by Itxaka** [comment]
I thougth it was 0 disabled, 1 permissive, 2 enforced. Seems that its not the case (anymore? was it ever?)
