### ISSUE TITLE
Renaming to elemental

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1380]
Currently we have several projects which are scattered that needs to be renamed to their `elemental-` counterpart.

This includes also refactoring code and documentation whenever necessary to reflect the renaming of each component.

**Comment by mudler** [comment]
https://github.com/rancher/elemental-toolkit/pull/1466

**Comment by mudler** [comment]
going over docs now 👀

**Comment by Itxaka** [comment]
hooks for elemental-cli seems to be broken with the move: https://github.com/rancher/elemental-toolkit/pull/1372/files
