### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1381]
The green pipeline is failing https://github.com/rancher-sandbox/cOS-toolkit/runs/6660771110?check_suite_focus=true
And the raw disk test on teal as well: https://github.com/rancher/elemental-toolkit/runs/6671951123?check_suite_focus=true

**Comment by Itxaka** [comment]
Raw disk is due to https://github.com/rancher/elemental-toolkit/commit/c1cd19241c14ef7496e5f287866560218c721906

Basically we were using recovery/cos-img for the raw disk, but that package no longer exists, so the raw image is basically an empty image with grub in it, no system.

Also, pretty bad in elemental that if we get an error from the luet installer we don not fail and just continue like its no big thing :D

**Comment by mudler** [comment]
seems now failures are just on the recovery test https://github.com/rancher/elemental-toolkit/runs/6719627524?check_suite_focus=true . cc @Itxaka didn't we already bumped the recovery image version?

**Comment by Itxaka** [comment]
we did, and it worked...

**Comment by mudler** [comment]
@mjura are you working on this? I see you are already working on https://github.com/rancher/elemental-cli/issues/219

**Comment by Itxaka** [comment]
Looks like the problem comes after the upgrade its done (active upgrade from recovery), we expect the os to be booted on the Active partition, but its instead booting on the fallback according to the serial logs:

```
Booting `cOS 0.8.14-1'


error: ../../grub-core/loader/arm64/efi/linux.c:92:invalid magic number.

error: ../../grub-core/loader/arm64/efi/linux.c:334:you need to load the kernel

first.


Press any key to continue...


   Falling back to `cOS 0.8.14-1'


error: ../../grub-core/loader/arm64/efi/linux.c:92:invalid magic number.

error: ../../grub-core/loader/arm64/efi/linux.c:334:you need to load the kernel

first.


Press any key to continue...


   Falling back to `cOS 0.8.14-1 (fallback)'


EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
```

**Comment by Itxaka** [comment]
Also, it may be a good idea to drop that `iota` thing from the testhelpers and use simple strings. Currently its confusing seeing those weird messages of expected 0 got 3, when we could have expected active got passive :)

**Comment by Itxaka** [comment]
and indeed that error seems to point out that the kernel is again not linked?

`error: ../../grub-core/loader/arm64/efi/linux.c:334:you need to load the kernel`

**Comment by Itxaka** [comment]
uh... why the vmlinuz does not appear AGAIN in the package? https://rancher-sandbox.github.io/cos-toolkit-package-browser/cos-toolkit-teal-arm64/system/kernel/0.1.2-8/

**Comment by Itxaka** [comment]
Also looks like we were not running the test-recovery before on arm64:
 - PR: https://github.com/rancher/elemental-toolkit/actions/runs/2410732599
 - Master: https://github.com/rancher/elemental-toolkit/actions/runs/2427626629

**Comment by Itxaka** [comment]
lmao, recovery has nothing in place to set the proper arm64 repo, so its defaulting to the x86 one

**Comment by mudler** [comment]
new failure https://github.com/rancher/elemental-toolkit/runs/6745496594?check_suite_focus=true , but I think I know what's going on as a similar error happened on c3os as well.. having a look

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/ele-testhelpers/pull/16

**Comment by mudler** [comment]
Now ARM image fails https://github.com/rancher/elemental-toolkit/runs/6760955814?check_suite_focus=true after https://github.com/rancher/elemental-toolkit/pull/1481 was merged :sweat_smile:

**Comment by mudler** [comment]
Also something with cosign is not right yet..? https://github.com/rancher/elemental-toolkit/runs/6762728107?check_suite_focus=true but maybe it needs its own card :/

**Comment by Itxaka** [comment]
If I'm reading properly, that run didn't include the changes from the new cosign, so it tried to pick the latest signatures from the old repo, but at that time the latest metadata files had their signatures pushed to the new one. Let's wait for tomorrow rebase to see if it's still happening, because that was properly building on the PR with a manual resign of master artifacts...

**Comment by Itxaka** [comment]
https://github.com/rancher/elemental-toolkit/pull/1485 for the arm builder

**Comment by Itxaka** [comment]
cosign success which doesn't set the COSIGN_REPOSITORY: https://github.com/rancher/elemental-toolkit/actions/runs/2450303215
