### ISSUE TITLE
Node with static IPs

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1402]
Add examples in our docs for:

- Node with static IPs
- Multiple NICs

**Comment by ldevulder** [comment]
Is bonding doable also? (for this card: https://github.com/rancher/elemental/issues/90)

**Comment by kkaempf** [comment]
> Is bonding doable also? (for this card: [rancher/elemental#90](https://github.com/rancher/elemental/issues/90))

It should. But I'd make this a separate card.

**Comment by mudler** [comment]
This card should be covered by https://github.com/rancher/elemental-toolkit/pull/1488
