### ISSUE TITLE
Remove cos-img package

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1465]
I believe the `cos-img` package should not be needed. Basically is currently only used to create the vanilla disk images. I believe the squashfs filesystem, if needed, should be created on the fly by the `elemental build-disk` command. This has couple of benefits:

* It makes easier to create vanilla images with any other image
* We can easily map squashfs compression options to the manifest.yaml.

I believe this change has no impact on the requested CI cycles (since we only use the squashfs recovery image for raw disks, hence it will be squashed only once), provides further flexibility and makes `packages/cos/` simpler.

**Comment by Itxaka** [comment]
This was kind of done and then reverted because the build-disk path needed the cos-img
