### ISSUE TITLE
COS_PERSISTENT on a F2FS partition howto ?

### ISSUE THREAD

**Issue by j-landru** [rancher/elemental-toolkit#1470]
**Is your feature request related to a problem? Please describe.**

As stated in https://github.com/rancher/elemental-toolkit/issues/1271 I plan to deploy a k3s cluster based on a single shared iso image overlaying node state and customization on COS_PERSISTENT labeled storage. For bare-metal node, I'd like to  set COS_PERSISTENT partition on a local  auxiliary block device (usb stick or other), as host SSD and disks will be fully dedicated to a distributed storage backend (probably Rook/Ceph and/or Longhorn based). I don't want to use node disk or partition to locally install elemental-toolkit cos-derivative. On such usb stick ou sdhc auxiliary device I'd like to use f2fs filesystem, to spare device lifetime, as k3s/k8s seems to be "write-heavy" for state preservation (on sqlite as well on etcd) : see  https://github.com/k3s-io/k3s/issues/5042.
  
**Describe the solution you'd like**

I'd like COS_PERSISTENT labeled storage hosted on a F2FS partition.

**Describe alternatives you've considered**

Can you point me, documentation and/or howtos for the best way to :
- build or find a f2fs compliant kernel, as default openleap  elemental-tolkit kernel of my ISO doesn't have CONFIG_F2FS_FS set,
- add F2FS module and f2fs-tools-static on initramfs to unify f2fs COS_PERSISTENT to root at boot,
- nota : f2fs-tools package will also have to be added to the cos container image.

**Additional context**

Nota : I'm a bit surprised about the today sudden naming change from cos-toolkit to elemental-toolkit, as my Alpine derivative is called "abcd : Alpine Based Cos Derivative" , I have to find a new acronym for my derivative ;o))

**Comment by frelon** [comment]
Hi @j-landru! 

I realize this comes very late, but we have some documentation to get LVM working, which might help with F2FS: https://elemental.docs.rancher.com/customizing/#adding-extra-lvm-volume-group-disks-during-the-installation

I'm closing this since it's been open a long time without interaction, feel free to reopen or post a new issue if this is still something you are working on!
