### ISSUE TITLE
Add audit package in base image

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1494]
While experimenting with SELinux and elemental I found frustrating no having the `audit` package installed within the base image. `audit` nicely keeps track SELinux runtime denials and similar events which could be really relevant for debugging purposes.

I am not sure if there is any reasoning to not include this package as part of the image or it is just not there because noone asked for.

**Comment by kkaempf** [comment]
added to ...elemental-testing:images/elemental-node-image
Not sure if `audit` is available in SLE Micro 🤔
