### ISSUE TITLE
#1516 introduced missing "cut" initrd dependency, breaking boot

### ISSUE THREAD

**Issue by kcburge** [rancher/elemental-toolkit#1517]
**cos-toolkit version:**
master

**CPU architecture, OS, and Version:**
amd64

**Describe the bug**
#1516 introduced a loop with cut command not found. System appears to hang until it drops to the rescue prompt.

**To Reproduce**
Build from latest green amd64 image and attempt to boot.

**Expected behavior**
Boot normally.

**Logs**
![image](https://user-images.githubusercontent.com/466165/173955084-13235562-35e8-432e-a554-47ff65e03cb3.png)

mount:
![image](https://user-images.githubusercontent.com/466165/173955119-c391d9d3-3d62-491b-b4fb-bf281a51ce3c.png)

**Comment by kcburge** [comment]
Update: I hacked my dracut config to include "cut" and this resolved the problem. Need to add "cut" to initrd or use alternative.

**Comment by davidcassany** [comment]
@kcburge thanks much for reporting! We are really sorry you had this issue, this should have never happened as this issue should have been caught by our CI. In fact this raised another issue within our CI setup we are currently fixing in order to prevent something like that to happen again.
