### ISSUE TITLE
Arm64 CI runners

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1530]
Have a general way to recreate and add self-hosted arm64 runners

- Terraform (?) template 
- Documentation

**Comment by aktech** [comment]
2 cents on self-hosting runners:

I built a service for running self-hosted GitHub Action runners on cloud with 0 maintenance and free for open source: https://cirun.io/

- It's on-demand, which means you only pay to your cloud provider for the time you're using it. It also supports arm based runners.
- All you need is a simple configuration .cirun.yml file, here is a [demo](https://www.youtube.com/watch?v=lDx0YVTn6yg).
- Also available on GitHub Marketplace as well: https://github.com/marketplace/cirun-io

**Comment by Itxaka** [comment]
terraform plan at https://github.com/rancher-sandbox/ele-runners-terraform

Docs updated in the private wiki

2 runners deployed

**Comment by Itxaka** [comment]
Pr merged with the info, runners already running jobs since yesterday.
