### ISSUE TITLE
Install quickstart doc pointing to an archived repository

### ISSUE THREAD

**Issue by e-minguez** [rancher/elemental-toolkit#1780]
https://github.com/rancher/elemental-toolkit/blob/a45bd221c477583504877f173ec63613dfd9db8e/docs/content/en/docs/Getting%20started/install.md?plain=1#L94

This repository is archived, it should point to this one

**Comment by frelon** [comment]
Yep, that's outdated! I will add it to https://github.com/rancher/elemental-toolkit/pull/1778
