### ISSUE TITLE
[Question] Debugging black screen after bootloader?

### ISSUE THREAD

**Issue by GrabbenD** [rancher/elemental-toolkit#1805]
I believe initrd is acting up but I'm not sure how to go about troubleshooting it in my custom image which is based on Arch Linux and has 6.4 kernel, dracut/initrd, grub2, amd microcode & firmware packages.

Is there any way to troubleshoot a black screen after selecting the image in the boot loader?

**Comment by kkaempf** [comment]
There should be some initial kernel messages 🤔 

Otherwise, `dracut` is probably to blame.
See https://docs.fedoraproject.org/en-US/quick-docs/debug-dracut-problems/ for debugging options 🤞🏻

**Comment by GrabbenD** [comment]
Changing the Green example from `opensuse/leap:15.4` to `opensuse/leap:15.5` fails at 
> dracut: dracut module 'livenet' cannot be found or installed.

**Comment by GrabbenD** [comment]
@kkaempf Do you happen to know any way of extracting logs from the container?

---

OpenSuSE Tumbleweed and Fedora 38 gets stuck at the same stage of the boot process but I'm unable to figure out why

When temporarily modifying the boot parameters (by pressing `e` in GRUB and appending additional parameters at the end of the `linux` line), I was able to establish that boot gets stuck at:
```console
[ OK ] Reached target basic.target - Basic System.
```
This was possible with `console=tty1` parameter. Furthermore appending `rd.break=initqueue` allows me to access the terminal just after this stage. However, `journalctl -b` isn't showing anything particularly useful since `less` isn't available in this shell (there's no scrolling to view the full log output) and I can't export any logs as no disks (`/dev/sd*`) are showing up, there's no persistent volumes available either (like `/usr/local`, `/system` or `/oem`)
```
systemd[1]: Reached target basic.target - Basic System
```

I also tried using `rd.shell rd.debug log_buf_len=1M` but this didn't show anything new.

---

I'm guessing dracut doesn't include the right modules to boot since next step should be to load storage controller modules after `basic.target` from my understanding. 

If I try to use the image directly (on bare metal) I get a black screen during initrd phase (which is also what happens with Arch Linux in Hyper-V)

**Comment by GrabbenD** [comment]
I workedaround missing disk modules by changing:
```Dockerfile
RUN elemental init -f
```
to:
```Dockerfile
# Todo find a better approach
RUN elemental init -f immutable-rootfs,grub-config,elemental-setup,cloud-config-defaults,cloud-config-essentials
RUN dracut --force --no-hostonly /boot/initrd --kver 6.3.12-200.fc38.x86_64
```

---

Now it fails at a different step:
```console
[FAILED] Failed to start initrd-switch-root.service - Switch Root.
```

Nonetheless now I'm able to access the logs 🙂 
Booting with:
```
console=tty1 rd.shell rd.debug
```
allows me to access the logs and save them to my persistent volume:
```console
mkdir -p /mnt && mount /dev/sda5 /mnt

cp /run/initramfs/rdsosreport.txt /mnt
journalctl -b > /mnt/journalctl.log
dmesg > /mnt/dmesg.log
systemctl status initrd-switch-root.service > /mnt/initrd-switch-root.service.log
```
[journalctl.log](https://github.com/rancher/elemental-toolkit/files/12098525/journalctl.log) / [dmesg.log](https://github.com/rancher/elemental-toolkit/files/12098527/dmesg.log) / [rdsosreport.txt](https://github.com/rancher/elemental-toolkit/files/12098529/rdsosreport.txt)

Looks like this is the issue:
```console
# initrd-switch-root.service.log
× initrd-switch-root.service - Switch Root
     Loaded: loaded (/usr/lib/systemd/system/initrd-switch-root.service; static)
     Active: failed (Result: exit-code) since Wed 2023-07-19 17:21:43 UTC; 2min 30s ago
    Process: 668 ExecStart=systemctl --no-block switch-root /sysroot (code=exited, status=1/FAILURE)
   Main PID: 668 (code=exited, status=1/FAILURE)
        CPU: 3ms

Jul 19 17:21:43 cos systemd[1]: Starting initrd-switch-root.service - Switch Root...
Jul 19 17:21:43 cos @ystemctl[668]: Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
Jul 19 17:21:43 cos systemd[1]: initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 17:21:43 cos systemd[1]: initrd-switch-root.service: Failed with result 'exit-code'.
Jul 19 17:21:43 cos systemd[1]: Failed to start initrd-switch-root.service - Switch Root.
Jul 19 17:21:43 cos systemd[1]: initrd-switch-root.service: Triggering OnFailure= dependencies.

```

**Comment by kkaempf** [comment]
adding @davidcassany

**Comment by kkaempf** [comment]
Btw, [this OBS project](https://build.opensuse.org/project/show/home:kwk:osimage) builds elemental packages for CentOS 8 and Fedora 38

[This project](https://build.opensuse.org/package/show/home:kwk:osimage/centos4r) shows a sample `Dockerfile` to build a CentOS 8 based image. This should be sufficient as a blueprint for a Fedora 38 image. 😉

**Comment by GrabbenD** [comment]
Thanks for sharing @kkaempf!

I tried it out and had to make some adjustments to successfully compile your Fedora 38 & CentOS 8 (like using right `--releasever`, refreshing repo in `--installroot`, removing `COPY *.repo`, removing `systemd-presets-branding-Elemental`, manually copying over elemental bin, renaming initramfs + kernel to: `/boot/initrd` + `/boot/vmlinuz` & adding missing dracut modules) but it ends up with the exact same boot error from above (meaning `initrd-switch-root.service` failing).

Even having the same issue with latest CentOS 9 and Fedora 39, same issue there :/


<details>
  <summary>Fedora 38</summary>
  
  ```Dockerfile
  # SPDX-License-Identifier: Apache-2.0
  # Define the names/tags of the container
  #!BuildTag: kwk/fedora/8:latest
  #!BuildConstraint: hardware:disk:size unit=G 8
  #
  
  # run `make build` to build local/elemental-toolkit image
  ARG TOOLKIT_REPO
  ARG VERSION
  FROM ${TOOLKIT_REPO}:${VERSION} as TOOLKIT
  
  # latest is the last stable release, does not include rawhide
  FROM quay.io/fedora/fedora:38 as host
  
  RUN mkdir /osimage
  
  RUN rpm --initdb --root /osimage
  
  RUN dnf --installroot /osimage update --nodocs --releasever 38 --refresh -y
  
  RUN dnf --installroot /osimage in --nodocs --releasever 38 -y filesystem
  
  # make system bootable
  RUN dnf --installroot /osimage in --nodocs --releasever 38 -y grub2 shim dracut kernel linux-firmware systemd bash
  
  #!ArchExclusiveLine: x86_64
  RUN if [ `uname -m` = "x86-64" ]; then dnf --installroot /osimage in --nodocs --releasever 38 -y syslinux; fi
  
  # make dracut happy
  RUN dnf --installroot /osimage in --nodocs --releasever 38 -y NetworkManager device-mapper tar curl ca-certificates dracut-live dracut-network dracut-squash dracut-tools
  
  # make ARM happy
  #!ArchExclusiveLine: aarch64
  RUN if [ `uname -m` = "aarch64" ]; then dnf --installroot /osimage in -y --nodocs --releasever 38 raspberrypi-firmware-uefi grub2-arm64-efi; fi
  
  # for obvious reasons
  #COPY fedora.repo /osimage/etc/yum.repos.d
  
  # dnf ... whatever
  #RUN dnf clean packages
  #RUN dnf makecache
  
  #RUN dnf --installroot /osimage --nogpgcheck in --nodocs -y elemental
  
  # make elemental-register happy
  #systemd-presets-branding-Elemental
  RUN dnf --installroot /osimage in --nodocs --releasever 38 -y dmidecode lvm2
  
  # make users happy
  RUN dnf --installroot /osimage in --nodocs --releasever 38 -y procps openssl openssh less iputils
  
  # for debugging
  RUN dnf --installroot /osimage in --nodocs --releasever 38 -y dnf
  
  FROM scratch as osimage
  
  COPY --from=host /osimage /
  
  ARG IMAGE_TAG=%VERSION%-%RELEASE%
  ARG IMAGE_REPO=%%IMG_REPO%%/kwk/osimage/fedora/38
  RUN echo IMAGE_REPO=\"${IMAGE_REPO}\"         >> /etc/os-release && \
      echo IMAGE_TAG=\"${IMAGE_TAG}\"           >> /etc/os-release && \
      echo IMAGE=\"${IMAGE_REPO}:${IMAGE_TAG}\" >> /etc/os-release && \
      echo TIMESTAMP="`date +'%Y%m%d%H%M%S'`" >> /etc/os-release && \
      echo GRUB_ENTRY_NAME=\"OS Image\" >> /etc/os-release
  
  # Ensure /tmp is mounted as tmpfs by default
  RUN if [ -e /usr/share/systemd/tmp.mount ]; then \
        cp /usr/share/systemd/tmp.mount /etc/systemd/system; \
      fi
  
  # Rebuild initrd to setup dracut with the boot configurations
  RUN dracut --no-hostonly --regenerate-all --force
  
  # HACK
  RUN mv /boot/initramfs-6.3.12-200.fc38.x86_64.img /boot/initrd
  RUN mv /boot/vmlinuz-6.3.12-200.fc38.x86_64 /boot/vmlinuz
  
  # Elemental
  COPY --from=TOOLKIT /usr/bin/elemental /usr/bin/elemental
  RUN elemental init -f immutable-rootfs,grub-config,elemental-setup,cloud-config-defaults,cloud-config-essentials
  ```
  
</details>

<details>
  <summary>CentOS 9</summary>
  
  ```javascript
  # SPDX-License-Identifier: Apache-2.0
  # Define the names/tags of the container
  #!BuildTag: kwk/centos/8:latest
  #!BuildConstraint: hardware:disk:size unit=G 8
  #
  
  # run `make build` to build local/elemental-toolkit image
  ARG TOOLKIT_REPO
  ARG VERSION
  FROM ${TOOLKIT_REPO}:${VERSION} as TOOLKIT
  
  # latest is the last stable release, does not include rawhide
  FROM quay.io/centos/centos:stream9 as host
  
  RUN mkdir /osimage
  
  RUN rpm --initdb --root /osimage
  
  RUN dnf --installroot /osimage update --nodocs --releasever 39 --refresh -y
  
  RUN dnf --installroot /osimage in --nodocs --releasever 39 -y filesystem
  
  # make system bootable
  RUN dnf --installroot /osimage in --nodocs --releasever 39 -y grub2 shim dracut kernel linux-firmware systemd bash
  
  #!ArchExclusiveLine: x86_64
  RUN if [ `uname -m` = "x86-64" ]; then dnf --installroot /osimage in --nodocs --releasever 39 -y syslinux; fi
  
  # make dracut happy
  RUN dnf --installroot /osimage in --nodocs --releasever 39 -y NetworkManager device-mapper tar curl ca-certificates dracut-live dracut-network dracut-squash dracut-tools
  
  # make ARM happy
  #!ArchExclusiveLine: aarch64
  RUN if [ `uname -m` = "aarch64" ]; then dnf --installroot /osimage in -y --nodocs --releasever 39 raspberrypi-firmware-uefi grub2-arm64-efi; fi
  
  # for obvious reasons
  #COPY *.repo /osimage/etc/yum.repos.d
  
  # dnf ... whatever
  #RUN dnf clean packages
  #RUN dnf makecache
  
  #RUN dnf --installroot /osimage --nogpgcheck in --nodocs -y elemental
  
  # make elemental-register happy
  # systemd-presets-branding-Elemental
  RUN dnf --installroot /osimage in --nodocs --releasever 39 -y dmidecode lvm2
  
  # make users happy
  RUN dnf --installroot /osimage in --nodocs --releasever 39 -y procps openssl openssh less iputils
  
  # for debugging
  RUN dnf --installroot /osimage in --nodocs --releasever 39 -y dnf
  
  FROM scratch as osimage
  
  COPY --from=host /osimage /
  
  ARG IMAGE_TAG=%VERSION%-%RELEASE%
  ARG IMAGE_REPO=%%IMG_REPO%%/kwk/osimage/CentOS/38
  RUN echo IMAGE_REPO=\"${IMAGE_REPO}\"         >> /etc/os-release && \
      echo IMAGE_TAG=\"${IMAGE_TAG}\"           >> /etc/os-release && \
      echo IMAGE=\"${IMAGE_REPO}:${IMAGE_TAG}\" >> /etc/os-release && \
      echo TIMESTAMP="`date +'%Y%m%d%H%M%S'`" >> /etc/os-release
  RUN echo GRUB_ENTRY_NAME=\"OS Image\" >> /etc/os-release
  
  # Ensure /tmp is mounted as tmpfs by default
  RUN if [ -e /usr/share/systemd/tmp.mount ]; then \
        cp /usr/share/systemd/tmp.mount /etc/systemd/system; \
      fi
  
  # Rebuild initrd to setup dracut with the boot configurations
  RUN dracut --no-hostonly --regenerate-all --force
  
  # HACK
  RUN mv /boot/initramfs-5.14.0-333.el9.x86_64.img /boot/initrd
  RUN mv /boot/vmlinuz-5.14.0-333.el9.x86_64 /boot/vmlinuz
  
  # Elemental
  COPY --from=TOOLKIT /usr/bin/elemental /usr/bin/elemental
  RUN elemental init -f immutable-rootfs,grub-config,elemental-setup,cloud-config-defaults,cloud-config-essentials
  ```
  
</details>

**Comment by GrabbenD** [comment]
I've tried to debug Fedora and Tumbleweed images further. Here's a summary of this thread:

# Fedora 38 / CentOS 9

[[Dockerfiles are above](https://github.com/rancher/elemental-toolkit/issues/1805#issuecomment-1643529844)]

### Problem
Boot gets stuck at:
```console
Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
```

### Logs

* `$ journalctl -b` [fedora_custom_journalctl.log](https://github.com/rancher/elemental-toolkit/files/12138388/fedora_custom_journalctl.log)
* `$ dmesg` [fedora_custom_dmesg.log](https://github.com/rancher/elemental-toolkit/files/12138386/fedora_custom_dmesg.log)
* `$ less /run/initramfs/rdsosreport.txt` [fedora_custom_rdsosreport.txt](https://github.com/rancher/elemental-toolkit/files/12138390/fedora_custom_rdsosreport.txt)
* `$ systemctl status initrd-switch-root.service` [fedora_custom_initrd-switch-root.service.log](https://github.com/rancher/elemental-toolkit/files/12138387/fedora_custom_initrd-switch-root.service.log)
* `$ less /etc/os-release` [fedora_custom_os-release.txt](https://github.com/rancher/elemental-toolkit/files/12138389/fedora_custom_os-release.txt)

### Cause?

I've verified that elemental setup was successful, there's services files here:
```console
/usr/lib/systemd/system/elemental-setup-boot.service
/usr/lib/systemd/system/elemental-setup-fs.service
/usr/lib/systemd/system/elemental-setup-initramfs.service
/usr/lib/systemd/system/elemental-setup-network.service
/usr/lib/systemd/system/elemental-setup-reconcile.service
/usr/lib/systemd/system/elemental-setup-reconcile.timer
/usr/lib/systemd/system/elemental-setup-rootfs.service
```
Furthermore the relevant service is enabled:
```console
$ systemctl is-enabled elemental-setup-rootfs.service
Configuration file /usr/lib/systemd/system/elemental-setup-rootfs.service is marked executable. Please remove executable permission bits. Proceeding anyway.
enabled
```
However, it _seems_ like none of the elemental scripts are executed while booting Fedora which makes `initrd-switch-root.service` fail as it depends on the outcome of `elemental-setup-rootfs.service`?

# Tumbleweed

[[Dockerfile from above](https://github.com/rancher/elemental-toolkit/issues/1805#issuecomment-1641638058)]

### Problem

The boot gets stuck on `dracut Initqueue hook...` stage. This error message is only visible after entering Dracut Emergency Shell:
```console
Warning: block:/dev/disk/by-label/COS_STATE does not exist
```

### Logs

* `$ journalctl -b` [tumbleweed_broken_journalctl.log](https://github.com/rancher/elemental-toolkit/files/12138441/tumbleweed_broken_journalctl.log)

* `$ dmesg` [tumbleweed_broken_dmesg.log](https://github.com/rancher/elemental-toolkit/files/12138438/tumbleweed_broken_dmesg.log)

* `$ less /run/initramfs/rdsosreport.txt` [tumbleweed_broken_rdsosreport.txt](https://github.com/rancher/elemental-toolkit/files/12138443/tumbleweed_broken_rdsosreport.txt)

* `$ blkid` [tumbleweed_broken_blkid.txt](https://github.com/rancher/elemental-toolkit/files/12138436/tumbleweed_broken_blkid.txt)

* `$ ls /dev/disk/by-label` [tumbleweed_broken_disk-by-label.log](https://github.com/rancher/elemental-toolkit/files/12138437/tumbleweed_broken_disk-by-label.log)

* `$ lsblk` [tumbleweed_broken_lsblk.txt](https://github.com/rancher/elemental-toolkit/files/12138442/tumbleweed_broken_lsblk.txt)

* `$ systemctl status elemental-setup-rootfs.service` [tumbleweed_broken_elemental-setup-rootfs.service.log](https://github.com/rancher/elemental-toolkit/files/12138439/tumbleweed_broken_elemental-setup-rootfs.service.log)

* `$ systemctl status initrd-switch-root.service` [tumbleweed_broken_initrd-switch-root.service.log](https://github.com/rancher/elemental-toolkit/files/12138440/tumbleweed_broken_initrd-switch-root.service.log)

# Cause

`/dev/disk/by-label/COS_STATE` actually exists. Perhaps the `block:` prefix is making it fail?

**Comment by frelon** [comment]
Hi @GrabbenD!

I was debugging this and ran into a problem with our dracut module for the immutable rootfs, I put the fix here: https://github.com/rancher/elemental-toolkit/pull/1820

Hopefully this will fix the "device does not exist" error!

**Comment by GrabbenD** [comment]
Thank you @frelon 
Leap and TW works as intended now!
