### ISSUE TITLE
Use non-FHS path as default for persistent state storage

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-toolkit#1830]
Right now we mount the persistent partition to `/usr/local` and put state-overlays/binds in `/usr/local/.state`.

This hides any applications installed in a derivative in `/usr/local` and I would propose we use some other path as default for this (`/.persistent` or `/run/elemental/persistent` comes to mind).

Users would still be able to make `/usr/local` into a persistent path, but our default would not mess with users expectations of a new system.

**Comment by davidcassany** [comment]
Yes we were wondering about that in the past and I think it actually makes a lot of sense. I think I'd vote to `/run/elemental/persistent`. This would also allow as to move as much as possible files introduced with `elemental init` into `/etc` or `/usr/local`, so we do not mess with distro provided stuff.
