### ISSUE TITLE
Move grub configuration out of state partition

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-toolkit#1848]
As discussed in https://github.com/rancher/elemental-toolkit/pull/1794#issuecomment-1757044517 we could move the grub configuration out of state partition.

This would mean we could skip adding the state partition for expandable images built using `build-disk` and also resize the recovery-image, resulting in a huge saving in space for disk images.

We can also consider adding a `--include-bootloader` (or any other understandable name) to reinstall grub during an upgrade procedure. Note this could potentially break the capability to boot a fallback image.

**Comment by kkaempf** [comment]
👍🏻 for smaller images

**Comment by frelon** [comment]
Upgrading the bootloader to be merged in #1906 closing this as done
