### ISSUE TITLE
None of the elemental-setup-*.service files  are owned by a package

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-toolkit#1896]
Running
~~~
rpm -qf /usr/lib/systemd/system/elemental-setup-*
~~~
shows `is not owned by any package` for all of them.

**Comment by frelon** [comment]
Yep, both this and the permission bits in #1895 are because of embedding+extracting in the init command. One way to get around both of these would be to wrap the embedded features in a tar/rpm and install it that way.

**Comment by kkaempf** [comment]
It will probably not be accepted to SLE as-is.

What's wrong with providing the respective `.service` files within the RPM ?

**Comment by davidcassany** [comment]
> It will probably not be accepted to SLE as-is.

I agree this is a bit uncommon. But we should consider them as user defined services. We could consider installing them in `/etc/systemd/system` so it is clear that those files are not necessarily provided by an RPM.

> What's wrong with providing the respective `.service` files within the RPM ?

Couples us a bit more to SUSE specifics. Having them embedded within the elemental-client binary makes possible the story of making simple Elemental OS out of any Linux OS including systemd, dracut and grub.

**Comment by kkaempf** [comment]
:+1: on the move to `/etc/systemd/system` then.
