### ISSUE TITLE
Create an upgrade test from an old installation to current PR

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1928]
This issue is devoted to explore and test different approaches regarding backward compatibility.

We currently test only downgrades (from current PR to and older system). We should also test the other direction. For that I'd suggest the following.

From an older system upgrade/download latest elemental client (the PR build) and use it to upgrade the old system to the latest and greatest OS (the PR build).

In addition we should also make sure that the old system is based on elemental-toolkit v1.1.1, hence probably we should also make a new v1.1.1 release.

**Comment by frelon** [comment]
I have published the containers `ghcr.io/rancher/elemental-toolkit/elemental-green:v1.1.1` and `ghcr.io/rancher/elemental-toolkit/elemental-green:v1.1.1` to use as a starting point for the upgrade tests.
