### ISSUE TITLE
Move recovery kernel and initrd out of recovery image

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1930]
Consider extracting the kernel, initrd and bootarguments in EFI partition to:

* Get closer to systemd-boot (it might be relevant in the future)
* Get rid of the loopback requirement in grub.cfg
* Make grub.cfg equivalent regardless of btrfs subvolumes or loop devices.

Requires matching kernel, initrd and args with snapshots and probably find a mechanism to actually asses the loaded kernel and initrd matches the appropriate snapshot.

**Comment by davidcassany** [comment]
I have been thinking further about it and I think that probably we could start by considering extracting the kernel and the initrd from the recovery image in a similar way we do the ISOs, this way the ISOs and RAW images would look almost the same. That would also allow us having squashfs compressed images for recovery and keep secure boot enabled.

**Comment by frelon** [comment]
ADR here: https://github.com/rancher/elemental-toolkit/wiki/ADRs#0001-extract-recovery-kernel
