### ISSUE TITLE
suc-upgrade: no such file or directory

### ISSUE THREAD

**Issue by nnewc** [rancher/elemental-toolkit#2024]
**elemental-toolkit version:** 

main branch

**CPU architecture, OS, and Version:**

 x86

**Describe the bug**

Using the example Dockerfile in `/examples/orange` I built an OSImage. When deploying the OS to existing cluster as an updateGroup via elemental-operator, the pod `apply-os-upgrader-ubuntu-on-rancher` fails to start with:

```bash
StartError (failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/sbin/suc-upgrade": stat /usr/sbin/suc-upgrade: no such file or directory: unknown)
```

**To Reproduce**

Run

```bash
make && FLAVOR=orange build-os
```

**Expected behavior**

Elemental cluster to be upgrade to ubuntu

**Comment by nnewc** [comment]
just also tried with default "green" flavor and also seeing the same issue.

```bash
make build-os
```

**Comment by frelon** [comment]
Hi @nnewc!

Awesome to see some experimentation with the toolkit!

The toolkit is itself agnostic from rancher provisioning and will not add the needed binaries, scripts and services, it will only generate the install media from the given container image.

The suc-upgrade script we use can be found [here](https://github.com/rancher/elemental/blob/main/framework/files/usr/sbin/suc-upgrade) and should be copied over to your image in the build step.

We also have a dev-image [here](https://github.com/rancher/elemental/blob/main/Dockerfile.dev.os) which might serve as an example.

Let me know how it goes! :+1:

**Comment by nnewc** [comment]
I can't seem to build the dev-image using the makefile. I get an error because the image `elemental-toolkit` and `elemental-register` is not present:

```bash
ERROR: failed to solve: docker.io/local/elemental-toolkit:dev: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: *** [Makefile:11: build-dev-os] Error 1
```

**Comment by frelon** [comment]
There is some docs here: https://github.com/rancher/elemental/blob/main/doc/DEVELOPMENT.md, seems like the toolkit image should be built using `make VERSION=dev build`

**Comment by frelon** [comment]
Closing this, feel free to reopen if you still run into issues!
