### ISSUE TITLE
Unformattable OEM partition

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-toolkit#2041]
**elemental-toolkit version:**
Successfully reproduced from v1.1.0 to v2.1.0

**Describe the bug**
elemental reset will fail when formatting the OEM partition:

```
ELEMENTAL_RESET_OEM="true" elemental --debug reset
```

Error:
```
INFO[2024-04-08T15:15:05Z] Formatting 'oem' partition                   
DEBU[2024-04-08T15:15:05Z] Running cmd: 'mkfs.ext4 -L COS_OEM /dev/vda2' 
DEBU[2024-04-08T15:15:05Z] 'mkfs.ext4' command reported an error: exit status 1 
DEBU[2024-04-08T15:15:05Z] 'mkfs.ext4' command output: mke2fs 1.47.0 (5-Feb-2023)
/dev/vda2 is apparently in use by the system; will not make a filesystem here! 
Error: 1 error occurred:
	* exit status 1
```

The problem seem to be jbd2 hugging this partition even after being unmounted.

```
# lsof | grep vda2
jbd2/vda2  820                      root cwd       DIR                7,0      350      21654 /
jbd2/vda2  820                      root rtd       DIR                7,0      350      21654 /
jbd2/vda2  820                      root txt   unknown                                        /proc/820/exe
```

For comparison, you can see that on a **working** system this is not the case after unmount:

```
recovery:~ # mount /oem
recovery:~ # lsof | grep vda2
jbd2/vda2 1426                            root  cwd       DIR                7,0     4096          2 /
jbd2/vda2 1426                            root  rtd       DIR                7,0     4096          2 /
jbd2/vda2 1426                            root  txt   unknown                                        /proc/1426/exe
recovery:~ # umount /oem
recovery:~ # lsof | grep vda2
recovery:~ # 
```

**To Reproduce**
I could narrow down this issue to [this commit](https://github.com/rancher-sandbox/cluster-api-provider-elemental/pull/39/commits/9d84bb9ca95c2e9604dc1a762dafda1800e5aa0f)

In this context I use an Elemental image built from scratch to build an ISO. 
The issue can be reproduced using Tumbleweed and Leap 15.5 base images.

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ./iso:/iso \
		--entrypoint /usr/bin/elemental docker.io/library/elemental-os:dev-kubeadm \
		--config-dir . --debug build-iso -n elemental-dev-kubeadm \
		--local -o /iso docker.io/library/elemental-os:dev-kubeadm
```

the last line `--local -o /iso docker.io/library/elemental-os:dev-kubeadm` works fine, but changing it to `-o /iso dir:/` will lead to this unformattable OEM issue.

**Comment by kkaempf** [comment]
wrong use within Dockerfile

**Comment by anmazzotti** [comment]
For future reference, this was mostly user error. 
The correct way of creating a bootable ISO is as [documented](https://elemental.docs.rancher.com/next/custom-images#create-a-custom-bootable-installation-iso):

Particularly importing the image as `os` and `builder` and build from the `rootfs` copy:

```Dockerfile
FROM registry.suse.com/suse/sle-micro/5.5:latest AS os

# The released OS already includes the toolchain for building ISOs
FROM registry.suse.com/suse/sle-micro/5.5:latest AS builder

WORKDIR /iso
COPY --from=os / rootfs
.
.
.
```
