### ISSUE TITLE
Make additional kernel parameters configurable

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-toolkit#2066]
When building ISOs for `aarch64` an additional `console=ttyS0` gets added to the kernel arguments.

This works nicely for Raspberry Pi but breaks on other ARM systems, like Nvidia Jetson which requires `ttyIC0`

Instead of [hard coding](https://github.com/rancher/elemental-toolkit/blob/6f0b28e113e728ab45b47dde5c050c8414c94bb3/pkg/action/build-iso.go#L45) the serial console, it should (at least) be a runtime parameter of the `build-iso` command.

I couldn't easily find other ways of adding kernel parameters in the  [documentation](https://elemental.docs.rancher.com/) :-(

**Comment by frelon** [comment]
Is this a duplicate of https://github.com/rancher/elemental-toolkit/issues/1764 ?

**Comment by kkaempf** [comment]
Indeed !
