### ISSUE TITLE
COS_GRUB too small on ARM / RPi

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-toolkit#2104]
Creating the boot partition seems to be based on the assumption "boot is always EFI".

So we see [EfiSize = MinPartSize](https://github.com/rancher/elemental-toolkit/blob/28c4e4735e5954f6c1a91b828ce3bc1c01e040f0/pkg/constants/constants.go#L47C2-L47C34) and `COS_GRUB` is created [with this minimal size](https://github.com/rancher/elemental-toolkit/blob/28c4e4735e5954f6c1a91b828ce3bc1c01e040f0/pkg/types/config.go#L525C4-L525C38).

However, this is wrong for ARM, esp. Raspberry Pi where everything (bootloader, firmware, kernel, initrd) must be on a `vfat` partition. The minimal size should be 256M for this `COS_GRUB` partitions.

The simplest change is probably to set `MinSize` to 256.

A better change would not use `EfiSize` for ARM since not all ARM systems boot via EFI. We probably need `BootSize` here 🤔

**Comment by kkaempf** [comment]
Seems as if I cannot override the default size via the `install:` config 😩 

From the [general configuration](https://rancher.github.io/elemental-toolkit/docs/customizing/general_configuration/) docs

~~~
 # default partitions
 # only 'oem', 'recovery', 'state' and 'persistent' objects allowed
 # size in MiB
  partitions:
~~~

**Comment by davidcassany** [comment]
When is the failure appearing? Is it at install time from an ISO?

> A better change would not use EfiSize for ARM since not all ARM systems boot via EFI. We probably need BootSize here 
Yes, probably we need a way to make all this more flexible. In fact adding the `efi` partition into this list should be easy. I can try to quickly prepare a PR for that.

**Comment by kkaempf** [comment]
What's probably more surprising - there's no error message during install about `COS_GRUB` overflowing 🤔

**Comment by kkaempf** [comment]
https://github.com/rancher/elemental-toolkit/pull/2105#issuecomment-2178210754 - reopening

**Comment by kkaempf** [comment]
this is done
