### ISSUE TITLE
Review and document supported yip keys

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-toolkit#2107]

**Comment by davidcassany** [comment]
I don't think we need additional documentation for the time being as all keys are documented in yip project README and this properly linked in our docs in `Cloud-config` reference section.

In the scope of this issue the `modules` plugin got removed rancher/yip#98.

I wonder if we should do the same for the `git` and `download` plugins. They both should be relatively simple to script with simple shell commands and they depend on third party libraries. I think they provide nice features, but I am not sure the additional dependencies for those is worth. Any thoughts?

**Comment by kkaempf** [comment]
👍🏻 on dropping `git` and `download` _if_ their dependencies are rather huge and/or unmaintained.
:-1: on dropping anything that can be scripted, but has minimal and well maintained dependencies.

**Comment by davidcassany** [comment]
I think they both can stay. `git` is relaying on a well maintained library ([go-git](https://github.com/go-git/go-git)) and download is based on a small library ([grab](github.com/cavaliergopher/grab)) which does not depend on anything else.

Closing this issue as I think a yip maintenance is done for now and docs are available and up to date.
