### ISSUE TITLE
Registry-Login

### ISSUE THREAD

**Issue by max06** [rancher/elemental-toolkit#2247]
**Is your feature request related to a problem? Please describe.**

I tried building a new derivation from scratch. Docker image is built fine. I'm stuck at building an iso-image, due to my registry not being publicly accessible. 

**Describe the solution you'd like**

A way to provide registry login credentials would be great.

**Describe alternatives you've considered**

I'd be happy to not use a registry for bulding my iso image, if someone tells me what to do after building the docker image.

**Additional context**

**Comment by max06** [comment]
hey @frelon, thanks for your reply!

I'm a little bit confused - the build-iso step is running in docker: `docker run --rm -ti -v $(pwd):/build ghcr.io/rancher/elemental-toolkit/elemental-cli:latest --debug build-iso --bootloader-in-rootfs -o /build oci:elemental-debian:latest`

Do I have to mount my docker socket so the build-iso step can get that image out of my docker daemon?

**Comment by frelon** [comment]
> hey @frelon, thanks for your reply!
> 
> 
> 
> I'm a little bit confused - the build-iso step is running in docker: `docker run --rm -ti -v $(pwd):/build ghcr.io/rancher/elemental-toolkit/elemental-cli:latest --debug build-iso --bootloader-in-rootfs -o /build oci:elemental-debian:latest`
> 
> 
> 
> Do I have to mount my docker socket so the build-iso step can get that image out of my docker daemon?

You got it! We mount it in the toolkit Makefile [here](https://github.com/rancher/elemental-toolkit/blob/7ac3f23384db657dbb268e98e40d72a5f4a4d73f/Makefile#L85)

**Comment by max06** [comment]
Oh no 🙈 
I had no clue about that makefile!

If I may suggest: The docs, especially the how to section, only shows direct docker commands to run. Adding the makefile there as well could solve some misunderstandings like this one.

Anyways, thanks a lot for the help! 
Happy holidays!

**Comment by frelon** [comment]
> Oh no 🙈 
> 
> I had no clue about that makefile!
> 
> 
> 
> If I may suggest: The docs, especially the how to section, only shows direct docker commands to run. Adding the makefile there as well could solve some misunderstandings like this one.

That's a good idea! Will look into it after the holidays! (Or accept as PR ;))

> 
> Anyways, thanks a lot for the help! 
> 
> Happy holidays!

No worries and happy holidays to you too!
