### ISSUE TITLE
Emergency workflow

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#389]
**Is your feature request related to a problem? Please describe.**
When encountering boot failures, we are dropped to the default dracut emergency shell.  We can think about other strategies to help the user in such scenarios via different ways (console hints, a workflow or steps to take). 

E.g. after being dropped to emergency shell and failing in restoring the system we could provide hints or tools to trigger an emergency cycle that can be for: reboot to fallback (fails) -> recovery (perform reset) -> active (no more reboots)

**Describe the solution you'd like**
A concise workflow to advice in case of emergency, annotated by hints during the process for the user. 

Let's say we are dropped to the dracut emergency shell, I should have some information on what to do next, and some cli tools to help me on doing maintenance ops like: changing default boot, identify booting issue caused by partitioning.

**Describe alternatives you've considered**
N/A, this ticket is mostly open for discussing the issue and ways to improve the current process

**Additional context**
#7 , #388

**Comment by davidcassany** [comment]
I would not only consider the dracut emergency shell. I would consider any emergency stage of systemd, which includes the dracut emergency shell, but not only. After switching root and no longer in initrd the boot can also fail and drop the user into an emergency shell (aka some volumes defined in fstab are not found or any required multi-user.target dependency fails).

**Comment by kkaempf** [comment]
not relevant any more
