### ISSUE TITLE
Add plain text metadata files along with the system images

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#434]
**Is your feature request related to a problem? Please describe.**

I'd like to easily check and collect minimal metadata of the other systems included into the installation. In other words, while running the active system I'd like to be capable to easily collect the version and some other details of the fallback system and the recovery system. With it I could easily check if I want to upgrade any of them, verify if they are up to the expected version or even run some integrity check. All without having to remount anything or reboot.

**Describe the solution you'd like**

First option that comes into my mind is to include an additional plain text file inside each partition to expose what is included in it. For instance in COS_RECOVERY partitions we could have a `recovery.meta` file including the checksum of the image, the version, the url, etc. So that I could easily now from the active partition which is the installed version or check its integrity running the checksum calculation over the actual image.

These files or data could be included, generated and consumed by the `installer/upgrader/deployer` tools. For instance, if running  `cos-upgrade --recovery` results on installing the same image this could be early detected and simply do nothing or check the integrity of the deployed one.

**Describe alternatives you've considered**

**Additional context**

Something like that could also be also beneficial for tests, so we could avoid having to reboot in many cases and reduce its timing execution.

I believe this could be a nice feature of #108

**Comment by frelon** [comment]
Implemented in https://github.com/rancher/elemental-cli/pull/278
