### ISSUE TITLE
vSphere

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#454]
This card is about having a packer template for vSphere

**Additional context**
Part of #208 

## Requirements
 - [ ] Check if it's possible to create a packer template that leverages https://github.com/rancher-sandbox/cos-toolkit-docs/pull/59 for installation, before attempting to create specific images
 - [ ] packer templates for vSphere
 - [ ] docs explaining how to use the packer templates

**Comment by frelon** [comment]
We will revisit cloud-images in the future, closing this.
