### ISSUE TITLE
Use shared galleries to share Azure images

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#465]
**Is your feature request related to a problem? Please describe.**
A way to use packer templates and cOS vanilla images from Azure easily with already published images. The implementation in #341 requires the user to manually import a vhda disk into Azure

**Describe the solution you'd like**
Find if we can use shared image gallery in Azure to share the cOS vanilla images with the world, and if we can do that easily, add it to our CI

**Additional context**

- https://github.com/rancher-sandbox/cOS-toolkit/issues/341#issuecomment-889158491
- https://www.packer.io/docs/builders/azure/arm#shared_image_gallery
- https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/windows/capture-image-resource.md
- https://docs.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries#generalized-and-specialized-images
- https://docs.microsoft.com/en-us/azure/virtual-machines/generalize
## Action items

- [ ] Find if we can use shared image gallery in Azure to share the cOS vanilla images with the world
- [ ] Add the process to our CI and adapt packer templates as necessary
- [ ] Offer a way to use directly our images in the packer templates, and/or update our docs on how to find the image in the shared gallery, or via `az` CLI

**Comment by Itxaka** [comment]
FYI, when I tried to used the shared gallery method as source with packer I found some issues:

```
==> azure-arm.cos: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Parameter 'osProfile' is not allowed.\",\r\n    \"target\": \"osProfile\"\r\n  }\r\n}"}]
```

So we may need to fix this upstream

**Comment by Itxaka** [comment]
ahh got it, its because the image is specialized:
```
Message: Parameter 'osProfile' is not allowed.
Cause: Admin username, password, or SSH keys were provided for a VM that was created from a specialized image version.
Workaround: Don't include the admin username, password, or SSH keys if you intend to create a VM from that image. Otherwise, use a generalized image version and supply the admin username, password, or SSH keys.
```

**Comment by Itxaka** [comment]
BTW @mudler @dragonchaser should we put this in front of the docs? Im currently doing the docs, but the packer templates are not working due to the shared image galley. 

should we fix this first? So the packer templates are working **and** we show how to use the shared image gallery or should we just drop teh shared image galley as a **source** and instead change the templates to use a manually build image based of the docs on build_raw_images.md ??

**Comment by Itxaka** [comment]
Thing is, there is also the possibility of having the target image being a shared image as well as part of the packer process...will we want this as derivatives may want to publish their images? (we kind of do this on aws...)

**Comment by mudler** [comment]
I would leave the shared galleries and the shared images story specifically to this card, also because that would involve also publishing Azure images as well, which I don't think it's something we should address right now - but it's fantastic to know how to do it and leave the door open in case we want to publish them.

**Comment by Itxaka** [comment]
In that case I need to revert the shared image gallery and just use plain images, which we already have info on how to create and upload to azure in the docs.
