### ISSUE TITLE
ARM/ARM64 Support

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#496]
This card is an Epic to track work related for supporting the ARM and ARM64 architectures:

- [x] #483 
- [x] #19
- [x] #521 
- [x] #524
- [x] #525 
- [x] #527 
- [x] #530
- [x] #676
- [x] #528
- [x] Pick platform to support (at least RPI or commercial boards for testing). What about Cavium/ThunderX?
- [x] #526 
- [x] #529

**Comment by kkaempf** [comment]
Everything's done.
