### ISSUE TITLE
cOS repositories for ARMv7 architectures (green flavor only)

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-toolkit#646]
We need the arm32 repositories to be published with all the packages compiled in order to extend our support for ARM.

Docker repositories were created during #524. This card is about running the pipelines on the arm workers in order to have all the packages published along with the CI process

There is currently low to no support of armv7 which means we would have a difficult time bulding packages correctly without support or a lot of work (for example, no squashfs packages exists for armv7 in opensuse ports repository)

We also have to take into account that we need a runner for the armv7 workflows. We could run them on graviton instances but we need to modify those to install all armhf architecture software for the runner to be able to work properly (binutils, docker, etc...)

We also need to take into account if there is a real necessity of supporting armv7 currently or all interest has moved to arm64 which we already have partial support for.

### Requirements

 - [ ] Viability of supporting armv7
 - [ ] General interest in armv7 cos toolkit
 - [ ] Arm runners armv7
 - [ ] Arm compatible workflows for armv7
 - [ ] Arms repositories with artifacts published for armv7

**Comment by Palando** [comment]
I would like to have an ARMv7 version. I have an Odroid MC1 cluster and would like to install cOS on it.

**Comment by Itxaka** [comment]
Hello there @Palando !

Thanks for the feedback, unfortunately our current efforts are pointed into a different direction as armv7 would require some heavy work (for example, no squash package for v7 on opensuse ports) and we don't have any of the hardware required to move this forward.

But we welcome any patches to support this if you have the proper hardware to build and test this! Feel free to ask any questions or open any issues that you find out and we will have a look at those.

Cheers!

**Comment by kkaempf** [comment]
Unsupported, sorry.
