### ISSUE TITLE
Test arm64 ISO on rpi 

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#731]
Now that we have merged #676, we need to test if the iso above is working on native hardware.

## Action Items

- [ ]  test installation
- [ ] test upgrade
- [ ] test reset
- [ ] test deploy raw disk image
- [ ] File new issues if new bugs are found and are not easily fixable

**Comment by mudler** [comment]
Blocked by #930

**Comment by kkaempf** [comment]
We don't have ISO but a [boot image](https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Dev:/Teal53/images/).
Closing.
