### ISSUE TITLE
ci: test suites to run on arm64

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#784]
Currently we run only the fallback tests for arm64: https://github.com/rancher-sandbox/cOS-toolkit/issues/733

however we want to run at least the smoke test and upgrade tests instead.

This card is to track the progress and to find out a way (also on native hardware) to run the above suites.

Reach out @kkaempf  before picking up this card

Follow up of https://github.com/rancher-sandbox/cOS-toolkit/issues/733

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/801
