### ISSUE TITLE
Test orange/blue flavors in x86_64 and arm64

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-toolkit#790]
We should at least have a manual test for both flavors+arches to see if they boot from iso/install from iso/boot disk after install to discover and write down any issues that we find.

We are currently pushing the artifacts, and they may as well be broken, so in that case, we should stop pushing them or fix them.

 - [ ] Orange x86_64 - boot from iso
 - [ ] Orange x86_64 - install from iso
 - [ ] Orange x86_64 - boot from hd after install
 - [x] Orange arm64 - boot from iso
 - [ ] Orange arm64 - install from iso
 - [ ] Orange arm64 - boot from hd after install
 - [ ] Blue x86_64 - boot from iso
 - [ ] Blue x86_64 - install from iso
 - [ ] Blue x86_64 - boot from hd after install
 - [x] Blue arm64 - boot from iso
 - [x] Blue arm64 - install from iso
 - [ ] Blue arm64 - boot from hd after install

**Comment by mudler** [comment]
We support only the green flavor, the other flavors (blue, orange) are published on a best-effort basis, any contribution is welcomed as we don't actively tests them.

My feeling about adding automated tests is that we are going book extra time with CI for something that is not really worth it

**Comment by Itxaka** [comment]
Blue arm64 iso (build from master, git hash c8d6ad5):

- [X] Blue arm64 - boot from iso

 - Seems to boot normally no issues that I could see

- [x] Blue arm64 - install from iso
 - Cannot install grub2 due to 
```Copying cOS..
Installing GRUB..
grub2-install: error: this utility cannot be used for EFI platforms because it does not support UEFI Secure Boot.
```
Probably need to install the shim package so it installs the shim which is supposed to be signed.
