### ISSUE TITLE
Be able to select the arch images automatically

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#791]
**Is your feature request related to a problem? Please describe.**
Now that we have multi-arch, each derivative should double the config file _just_ for specifying the repository corresponding to the arch in the config file ( when building a derivative with docker)

**Describe the solution you'd like**
A derivative developer shouldn't need to hardcode the architecture in any of my scripts or in the config file.  So If the build on some host architecture it just builds for that architecture. The `luet` config file at the moment requires to specify the repositories which have a different image name for each architecture.

Possible approaches:
- Have a CI job that after publish collect tags and links them correctly to the image manifest
- Have a way from the config file to specify the arch: e.g. if there was a just a `arch: amd64` field in the repo definition that if set will only be enabled if the host arch matches. Maybe this can be implemented as a plugin/extension (https://luet-lab.github.io/docs/docs/concepts/plugins-and-extensions/)

**Describe alternatives you've considered**
https://github.com/mudler/luet/issues/230

**Additional context**

**Comment by Itxaka** [comment]
> Now that we have multi-arch, each derivative should double the config file just for specifying the repository corresponding to the arch in the config file

well...it makes sense? packages are not the same in the arches and it need some extra stuff per arch.

Of course, we could also make luet aware of config files with different arches like we do with the github workflow configs? so if it finds a values files with an arches key, it loads the `arches.ARCH` for whatever arch is running on or overridable by flag like it was the normal values?

That would make it simple, straightforward and most importantly, would not break backwards compatibility.

This is only for building of course, which I think this is what this card its about? Althought it could be worded better as its a bit confusing on what this refers to. What is the config file? Is it the values file?

**Comment by mudler** [comment]
cc @ibuildthecloud
