### ISSUE TITLE
incorrectly nested compression makes qemu downloads 300M bigger

### ISSUE THREAD

**Issue by JanZerebecki** [rancher/elemental-toolkit#882]
**cos-toolkit version:** 0.7.4-4-gf80dee22

**CPU architecture, OS, and Version:** not applicable

**Describe the bug**

The qemu images could be much smaller First gz then xz compression wastes about 300M.

**To Reproduce**

Download qemu image and extract it, then only compress it with, then compare:
$ xz --keep -9 cOS
$ ls -s1h
total 5,6G
2,4G cOS
1,2G cOS-Packer-green-0.7.4-4-gf80dee22-QEMU-x86_64.tar.gz
1,2G cOS-Packer-green-0.7.4-4-gf80dee22-QEMU-x86_64.tar.gz.tar.xz
919M cOS.xz

**Expected behavior**

Smaller downloads.

**Logs**

**Additional context**

**Comment by mudler** [comment]
Thanks for the issue report!

**Comment by Itxaka** [comment]
problem is packer doesnt support xz compression out of the box: https://www.packer.io/docs/post-processors/compress#supported-formats

But we are not even using the compressed files anyway I can see? Like yeah, we upload them but...we keep downloading the box files instead...

And Im not even sure where that tar.gz files are coming from, like we should only download the box files:

```
Artifact cOS-Packer-nonsquashfs-green-vbox-x86_64.box was downloaded to /home/runner/work/cOS-toolkit/cOS-toolkit/release
Artifact cOS-Packer-nonsquashfs-green-QEMU-x86_64.box was downloaded to /home/runner/work/cOS-toolkit/cOS-toolkit/release
```

????

**Comment by JanZerebecki** [comment]
Weird, then where does the .xz at the end come from? All assets on the github release page have it. I downloaded https://github.com/rancher-sandbox/cOS-toolkit/releases/download/v0.7.4/cOS-Packer-green-0.7.4-4-gf80dee22-QEMU-x86_64.tar.gz.tar.xz then extracted it unxzed, untared, ungziped, untared it to get to the qcow image.

**Comment by Itxaka** [comment]
Xz artifacts are compressed with the GitHub action that does the releases. I'm more interested in knowing where those tar.gz came from as it seems that only the .box files should be released and compressed with xz. Like we don't even use those tar.gz files in our pipeline anywhere that I can see!

**Comment by JanZerebecki** [comment]
Perhaps this line?:
https://github.com/rancher-sandbox/cOS-toolkit/blob/b5d965f36bb6bc9b8b6795c5b6a1d1a4e75ce4e8/.github/workflows/build-releases-green-x86_64.yaml#L756

**Comment by Itxaka** [comment]
yeah, that builds the tar.gz files in the workflow, but during the release part that file is not downloaded https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/workflows/build-releases-green-x86_64.yaml#L723

only the .box https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/workflows/build-releases-green-x86_64.yaml#L751 and the qcow https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/workflows/build-releases-green-x86_64.yaml#L756 images are downloaded to the release dir...which should results in only those artifacts being compressed with xz and released...

**Comment by Itxaka** [comment]
ah I see, we upload the tar.gz with a wrong name for some reason! https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/workflows/build-releases-green-x86_64.yaml#L292 we upload the tar.gz with the `.ova` name

**Comment by Itxaka** [comment]
Umm, testing the xz compression, its a bit slow for us to insert it into the pipeline. It takes about 20 seconds to compress the artifacts to tar.gz (on a free github node), while xz (in a more faster machine with nvme disk) it took more than 9 minutes (`xz --keep -9 cOS  575.99s user 1.04s system 99% cpu 9:37.06 total`) which is more than double our image building time (full process from iso to box files!)

Maybe we could do an uncompress on the release part instead and let the releaser compress the artifacts itself so it doesnt affect our PR workflows...

**Comment by JanZerebecki** [comment]
Maybe even drop the tar.gz step from packer completely, so only the release compression remains?
