### ISSUE TITLE
when downloading an image provide a way to verify it is trusted

### ISSUE THREAD

**Issue by JanZerebecki** [rancher/elemental-toolkit#904]
**Is your feature request related to a problem? Please describe.**

The usual way when I use an iso/qcow/raw image is to obtain a web of trust path to the publisher and verify the signature on the image. I couldn't find a signature on the Github assets. Being able to only run known code is a quality many people want.

**Describe the solution you'd like**

Usually to establish supply chain security one would have reproducible builds and have a set of people who have cross-signed identities and have one of them reproduce the official artifact of the project, verify that they match, sign them and upload the signature. (Will need to test if all the inputs are either signed source or reproducible themselves. For intermediary results that are cached or published it is usually a good idea to also sign them. There seem to be signatures at some levels in cOS, but I haven't investigated them, yet. This git repo uses a workflow that recreates commits and tags on Github, so the original signature is gone if there was any.)

**Describe alternatives you've considered**

* Not run cOS for production purposes.
* Always build from git source. (Still needs signed git commits and/or tags.)
* Use source and binary transparency without signatures. (More complicated, basic tools less implemented, would probably be more centralized.)
* Use a trusted build host to sign. (This is the historical approach.)

**Additional context**

**Comment by Itxaka** [comment]
we may be able to get away with this by using the same process we use with the artifacts, signing the iso blob with cosign keyless mode, but we would need to store the signature along and make it part of the release.

**Comment by Itxaka** [comment]
quick tests shows that this is possible, but only with the latest (development) version of cosign. This should be included in cosign 1.4.0:

Sign:
```
$ COSIGN_EXPERIMENTAL=1 cosign sign-blob cOS-0.20211130.iso --output-signature=signature
Using payload from: cOS-0.20211130.iso
Generating ephemeral keys...
Retrieving signed certificate...
Your browser will now be opened to:
https://oauth2.sigstore.dev/auth/auth?access_type=online&client_id=sigstore&code_challenge=FYgB54KiLIn8BzAluSEaaU__qQymsrMNthBkQTCrkU8&code_challenge_method=S256&nonce=21dLhHTUIlZUC8BadiOu3581ANs&redirect_uri=http%3A%2F%2Flocalhost%3A42365%2Fauth%2Fcallback&response_type=code&scope=openid+email&state=21dLhDENEuzftdrjhj5b221PKUg
Successfully verified SCT...
signing with ephemeral certificate:
-----BEGIN CERTIFICATE-----
MIICojCCAimgAwIBAgIUAICCgdVQVFuQWyZakSAW9zJNcjYwCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MTExMzAwOTU1MzhaFw0yMTExMzAxMDE1MzdaMAAwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAATUQJ1F+gy3x+c5AO3tQvigYuAdHUSNC5HiPfJYn5S1fkWqJ0O6372e
1nghhPaMOwHoJ3KVAE4vxhP8z1mMKwOno4IBVTCCAVEwDgYDVR0PAQH/BAQDAgeA
MBMGA1UdJQQMMAoGCCsGAQUFBwMDMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKcV
jKyR7dp3RFwlk4PZ8ZXZOeIHMB8GA1UdIwQYMBaAFMjFHQBBmiQpMlEk6w2uSu1K
BtPsMIGNBggrBgEFBQcBAQSBgDB+MHwGCCsGAQUFBzAChnBodHRwOi8vcHJpdmF0
ZWNhLWNvbnRlbnQtNjAzZmU3ZTctMDAwMC0yMjI3LWJmNzUtZjRmNWU4MGQyOTU0
LnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vY2EzNmExZTk2MjQyYjlmY2IxNDYvY2Eu
Y3J0MB4GA1UdEQEB/wQUMBKBEGlnYXJjaWFAc3VzZS5jb20wLAYKKwYBBAGDvzAB
AQQeaHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoMAoGCCqGSM49BAMDA2cA
MGQCMBk+ny6AtWmnD6vf6kZimZr1pma2MfZ4+8CTWcJRh3pycFgGdjctFOGuHaKz
iYvNxAIwO3evRpiqAVh1MXZourgde7ad9NTjvscGOFyrTopuyv7A36HB2FwpKDJH
F7Xg2kf4
-----END CERTIFICATE-----

tlog entry created with index: 900500
Signature wrote in the file signature
```

Verify:

```
$ COSIGN_EXPERIMENTAL=1 cosign verify-blob cOS-0.20211130.iso --signature signature     
Certificate is trusted by Fulcio Root CA
Email: [igarcia@suse.com]
Issuer:  https://github.com/login/oauth
Verified OK
tlog entry verified with uuid: "1847e0bf7c3427a8c5957af9b22f775e26e84c728347ac32e083838f2e7c2a7d" index: 900500
```

**Comment by mudler** [comment]
From a Derivative point of view cosign can be used to verify the container images: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/creating-derivatives/creating_bootable_images/#using-cosign-in-your-derivative . Artifacts generated from the build process are signed and pushed over the container registry with cosign in keyless mode. 

We need to be sure to build in a secured environment which is trusted.

For ISOs, raw disk, and other artifacts we could use cosign as @Itxaka just mentioned

**Comment by JanZerebecki** [comment]
The design of cosign keyless mode makes no sense. Based on that and other issues I'd suggest to avoid cosign entirely until cosign is willing to address this. See: https://lwn.net/Articles/849244/ and https://lwn.net/Articles/849241/
Replacing the GPG code base is probably a good idea, which https://sequoia-pgp.org/ provides.
Transparency logs like sigstore don't offer the guarantees that some claim for it, as critical parts are not implemented: See: https://lwn.net/Articles/849243/ and https://gitlab.com/JanZerebecki/transparency-log-watcher and https://lobste.rs/s/phrfzu/gossamer_supply_chain_security_for_open#c_vzsyjz

**Comment by mudler** [comment]
> The design of cosign keyless mode makes no sense. Based on that and other issues I'd suggest to avoid cosign entirely until cosign is willing to address this. See: https://lwn.net/Articles/849244/ and https://lwn.net/Articles/849241/ Replacing the GPG code base is probably a good idea, which https://sequoia-pgp.org/ provides. Transparency logs like sigstore don't offer the guarantees that some claim for it, as critical parts are not implemented: See: https://lwn.net/Articles/849243/ and https://gitlab.com/JanZerebecki/transparency-log-watcher and https://lobste.rs/s/phrfzu/gossamer_supply_chain_security_for_open#c_vzsyjz

Thanks for the helpful insight! Can https://sequoia-pgp.org/ sign containers too? That's our main use-case we have with cosign. Relying on the same tool makes things easier to maintain.

An option would also be to switch to cosign with keys, instead of keyless.

**Comment by Itxaka** [comment]
Maybe we should have a chat, including @JanZerebecki and @flavio so we can shed some light on this? on my part I can only say that I know this in a very superficial way so I may not understand the implications that Jan is mentioning.

**Comment by JanZerebecki** [comment]
Another design problem with cosign is that it was started in 2021 and restricts itself to create keys as NIST P256 instead of e.g. Curve25519. See: https://safecurves.cr.yp.to/
Though that can probably be worked around with creating the key with another tool.

I'll need to do some more digging re container signing. And should probably file an issue upstream at sigstore/cosign.

If you think some voice chat will help, I can do that.

**Comment by flavio** [comment]
Keyless signing is just one of the options offered by sigstore to sign objects. This is being used here because, thanks to the Oauth integration of GitHub action, it's provides an easier and safer way to sign the artifacts produced by elemental build pipelines.

My understanding is that keyless signing is not going to be used for the builds Rancher will offer to its customers. These builds will be done in a fully controller environment (unlike GH actions) and will probably use key-based signing.

As for the feedback about sigstore fallacies, I suggest you to reach to the upstream community. This would be the best place to tackle them

**Comment by flavio** [comment]
> Thanks for the helpful insight! Can https://sequoia-pgp.org/ sign containers too? That's our main use-case we have with cosign. Relying on the same tool makes things easier to maintain.

This is what Red Hat is doing right now. However the signature cannot be checked with containerD, which is what we currently care about.

BTW, Red Hat is directly contributing to sigstore.

**Comment by frelon** [comment]
Elemental-toolkit will not provide images anymore, closing this. (signing should be implemented on an individual derivative basis).
